# Generated by Django 5.0.6 on 2024-09-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='full_premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_of_id_and_volunteer', models.IntegerField()),
            ],
        ),
    ]
