# Generated by Django 5.0.6 on 2024-12-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_status',
            field=models.BooleanField(default=False),
        ),
    ]
